/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

// #include "rand.h"


// void
// rand_prog_1(char *host)
// {
// 	CLIENT *clnt;
// 	void  *result_1;
// 	long  initialize_random_1_arg;
// 	double  *result_2;
// 	char *get_next_random_1_arg;

// #ifndef	DEBUG
// 	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
// 	if (clnt == NULL) {
// 		clnt_pcreateerror (host);
// 		exit (1);
// 	}
// #endif	/* DEBUG */

// 	result_1 = initialize_random_1(&initialize_random_1_arg, clnt);
// 	if (result_1 == (void *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// 	result_2 = get_next_random_1((void*)&get_next_random_1_arg, clnt);
// 	if (result_2 == (double *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// #ifndef	DEBUG
// 	clnt_destroy (clnt);
// #endif	 /* DEBUG */
// }


// int
// main (int argc, char *argv[])
// {
// 	char *host;

// 	if (argc < 2) {
// 		printf ("usage: %s server_host\n", argv[0]);
// 		exit (1);
// 	}
// 	host = argv[1];
// 	rand_prog_1 (host);
// exit (0);
// }


// Usage example.
// ./rand_client cspro2.sogang.ac.kr 20 10
// client procedure,	server domain,	seed,		iteration
// argv[0],				argv[1],		argv[2],	argv[3]	

#include <stdlib.h>
#include <stdio.h>
#include "rand.h"

void main(int argc, char *argv[ ]) {
	int iters,i;
	long myseed;
	CLIENT *clnt;
	void *result_1;
	double *result_2;
	char *arg;
	if ( argc != 4 ) {
		fprintf(stderr, "Usage: %s host seed iterations\n", argv[0]);
		exit(1);
	}
	clnt = clnt_create(argv[1], RAND_PROG, RAND_VERS, "udp");

	if ( clnt == (CLIENT *) NULL ) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	myseed = (long) atoi (argv[2]);
	iters = atoi (argv[3]);

	result_1 = initialize_random_1(&myseed, clnt);		// Remote Procedure Call

	if (result_1 == (void *) NULL) {
		clnt_perror(clnt, "call failed");
	}

	for( i=0; i<iters; i++) {
		result_2 = get_next_random_1((void *)&arg, clnt);		// Remote Procedure Call
		if (result_2 == (double *) NULL) {
			clnt_perror(clnt, "call failed");
		}
		else {
			printf("%d : %f\n", i, *result_2);
		}
	}

	clnt_destroy(clnt);
	exit(0);
}