/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

char *
convert_expression_1_svc(char *argp, struct svc_req *rqstp)
{
	static char  result;

	/*
	 * insert server code here
	 */

	return &result;
}

long *
calculate_expression_1_svc(char *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */

	return &result;
}
