/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

// #include "calc.h"


// void
// calc_prog_1(char *host)
// {
// 	CLIENT *clnt;
// 	double  *result_1;
// 	char * calculate_expression_1_arg;

// #ifndef	DEBUG
// 	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
// 	if (clnt == NULL) {
// 		clnt_pcreateerror (host);
// 		exit (1);
// 	}
// #endif	/* DEBUG */

// 	result_1 = calculate_expression_1(&calculate_expression_1_arg, clnt);
// 	if (result_1 == (double *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// #ifndef	DEBUG
// 	clnt_destroy (clnt);
// #endif	 /* DEBUG */
// }


// int
// main (int argc, char *argv[])
// {
// 	char *host;

// 	if (argc < 2) {
// 		printf ("usage: %s server_host\n", argv[0]);
// 		exit (1);
// 	}
// 	host = argv[1];
// 	calc_prog_1 (host);
// exit (0);
// }



/*
Produced by Raphael Cho.
Creation Date: 2022-12-11-Sun.
Last Modification Date: 2022-12-12-Mon.
*/


#include "calc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_STR_LEN 100

void main (int argc, char *argv[ ])
{
	CLIENT *clnt;
	double  *result_1;
	// char  calculate_expression_1_arg;

    // Get command-line arguments.
	if ( argc != 2 ) {
		fprintf(stderr, "Usage: ./calc_client host \n");
		exit(1);
	}

	// Stub create?!
	clnt = clnt_create (argv[1], CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}
    
    char* arith = (char *) malloc (MAX_STR_LEN);
    scanf("%s", arith);
	// strcpy (arith, argv[2]);

	result_1 = calculate_expression_1 (&arith, clnt);	// Remote Procedure Call 1.
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    printf("The answer is %d\n", (int) *result_1);
    printf("The answer is %f in floating number\n", *result_1);

	// Stub destroy?!
	clnt_destroy(clnt);
	exit(0);
}
